onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /Riscv_Multi_Cycle_tb/clk
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/clk
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/reset
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/Op
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/Funct3
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/Funct7
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/Zero
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/PC_En
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/I_or_D
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/Mem_Write
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/IR_Write
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/Mem_to_Reg
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/Reg_Write
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/ALU_Src_A
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/ALU_Src_B
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/ALU_Control
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/PC_Src
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/PC_Write
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/Branch
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/Branch_n
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/ALU_Op
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/imm_gen/funct3
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/imm_gen/funct7
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/imm_gen/imm
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/imm_gen/opcode
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/imm_gen/rd
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/imm_gen/rs1
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/imm_gen/rs2
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_a_input/Selector
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_a_input/I_0
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_a_input/I_1
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_a_input/I_2
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_a_input/I_3
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_a_input/Mux_Out
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_b_input/Selector
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_b_input/I_0
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_b_input/I_1
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_b_input/I_2
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_b_input/I_3
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/mux_b_input/Mux_Out
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Alu/Result
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Alu/A
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Alu/B
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Alu/Control
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Pc/D
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Pc/Q
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/instr_or_data/Mux_Out
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/MemCtrl/ADDRIn
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/MemCtrl/ADDROut
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/MemCtrl/Sel
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/ROM/Address
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/ROM/Instruction
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/ROM/rom
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/RAM/Address
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/RAM/Write_Data
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/RAM/ram
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/RAM/Write_Enable
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/peripheral_mux/Selector
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/peripheral_mux/I_0
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/peripheral_mux/I_1
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/peripheral_mux/I_2
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/peripheral_mux/I_3
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/peripheral_mux/Mux_Out
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Decoder_rv32I/instr
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/IR_opcode/Q
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Reg_file/sp/Q
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Reg_file/ra/Q
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Reg_file/a2/Q
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Reg_file/a0/Q
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Reg_file/t0/Q
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/Control/State_and_Signals/state
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Result_register/D
add wave -noupdate /Riscv_Multi_Cycle_tb/UUT/DataPath/Result_register/Q
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 2} {1640906 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 359
configure wave -valuecolwidth 173
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1546902 ps} {1713533 ps}
